# Generated by Django 2.0.6 on 2018-06-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Czas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomieszczenie', models.CharField(max_length=100)),
                ('studia', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('tyg', models.CharField(max_length=100)),
                ('dzien', models.CharField(max_length=100)),
                ('godz', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Prowadzacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zajecia', models.ManyToManyField(to='validator.Czas')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zajecia', models.ManyToManyField(to='validator.Czas')),
            ],
        ),
    ]
